### ISSUE TITLE
没有 `operator ->`……

### ISSUE THREAD

**Issue by LYP951018** [lichray/xrangexx#2]
话说 `operator ->` 不是 [`InputIterator`](http://en.cppreference.com/w/cpp/concept/InputIterator) 的条件之一吗
还有就是，我感觉可以把这个扩展成支持所有可自增的东西，仿出一个 [up-to Expression](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0268r0.pdf)

**Comment by lichray** [comment]
`(*i).m` is not valid so there is no `i->m`.  Show me an actual issue you found in a generic algorithm.

**Comment by FrankHB** [comment]
See also http://stackoverflow.com/questions/34949766/implementing-operator-in-a-range-adaptors-iterator-class.

BTW, `reference` has failed to meet [forward.iterators]/1.

**Comment by lichray** [comment]
> BTW, reference has been also violated [forward.iterators]/1.

I know, but that's the status quo for proxy iterators, and things like this.

> See also http://stackoverflow.com/questions/34949766/implementing-operator-in-a-range-adaptors-iterator-class.

It's only a problem when the Ranges TS is merged into the standard, where `.operator->()` is explicitly checked.  For now, you are not going to have a generic library relying on `->` to work, since based on the current specification in the standard, you can only check `i->m`, not the operator.  Since there is no `m`, the requirement is voidly satisfied.  Unless you can come up with a counter example, showing your legitimate, generic code doesn't compile against this.

**Comment by FrankHB** [comment]
> Since there is no `m`, the requirement is voidly satisfied.

Plausible. It seems [structure.requirements]/4 does not clearly mandate the expression listed in the tables being well-formed or not, and Table 106 also does not state what is `m`. However, [iterator.requirements.general]/1 has stated only well-defined `(*i).m` should be considered. Thus this issue is resolved.

**Comment by lichray** [comment]
> It's only a problem when the Ranges TS is merged into the standard, where .operator->() is explicitly checked.

Well no, I misread Ranges TS.  In the latest working draft (n4569), the `i->m` requirement is simply removed.  Iterators are free to provide `->`.

**Comment by FrankHB** [comment]
> Well no, I misread Ranges TS. In the latest working draft (n4569), the `i->m` requirement is simply removed. Iterators are free to provide `->`.

Well, do you know when will it be integrated into the working paper? Will C++17 loose the requirements on iterators and eventually resolve [the proxy iterator problems](http://ericniebler.com/2015/01/28/to-be-or-not-to-be-an-iterator/)?

**Comment by lichray** [comment]
> Well, do you know when will it be integrated into the working paper?

C++20, probably.  Ranges TS has been sent out for ballot, may be published later this year, but will not catch up C++17.

> Will C++17 loose the requirements on iterators and eventually resolve the proxy iterator problems?

No.  The work on proxy iterators (p0022r1) is based on Ranges TS.

**Comment by FrankHB** [comment]
> C++20, probably. Ranges TS has been sent out for ballot, may be published later this year, but will not catch up C++17.

Sadly, I can't wait longer. Perhaps I have to reinvent the wheel again...

One more off-topic issue: you have used reserved identifier in the header guard...

**Comment by lichray** [comment]
> Sadly, I can't wait longer. Perhaps I have to reinvent the wheel again...

Just use https://github.com/ericniebler/range-v3 ; there is no need to limit yourself to the standard library in a practical project.

> One more off-topic issue: you have used reserved identifier in the header guard...

Yea, whatever... Another way to look at this is, this is a "standard" header by its own, and hope that does not clash with other headers in your standard library implementations :)
